# Generated by Django 6.0.5 on 2026-05-19 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do campeonato')),
                ('game', models.CharField(max_length=100, verbose_name='Nome do jogo')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('OPEN', 'Inscrições abertas'), ('IN_PROGRESS', 'Em andamento'), ('FINISHED', 'Finalizado')], default='DRAFT', max_length=11, verbose_name='Status do campeonato')),
                ('max_teams', models.PositiveIntegerField(verbose_name='Número máximo de times')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('stage_format', models.CharField(choices=[('SINGLE_ELIMINATION', 'Eliminação simples'), ('DOUBLE_ELIMINATION', 'Eliminação dupla'), ('ROUND_ROBIN', 'Pontos corridos'), ('GROUP_THEN_PLAYOFFS', 'Fase de grupos + playoffs')], max_length=19, verbose_name='Formato do campeonato')),
                ('group_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de grupos')),
                ('teams_per_group', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de times por grupo')),
                ('teams_advancing_per_group', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de times que avançam por grupo')),
                ('group_match_format', models.CharField(blank=True, choices=[('BO1', 'Melhor de 1'), ('BO3', 'Melhor de 3'), ('BO5', 'Melhor de 5')], max_length=3, null=True, verbose_name='Formato das partidas no grupo')),
                ('playoff_format', models.CharField(blank=True, choices=[('SINGLE_ELIMINATION', 'Eliminação simples'), ('DOUBLE_ELIMINATION', 'Eliminação dupla')], max_length=18, null=True, verbose_name='Formato do playoff')),
                ('playoff_match_format', models.CharField(blank=True, choices=[('BO1', 'Melhor de 1'), ('BO3', 'Melhor de 3'), ('BO5', 'Melhor de 5')], max_length=3, null=True, verbose_name='Formato das partidas no playoff')),
                ('final_match_format', models.CharField(blank=True, choices=[('BO1', 'Melhor de 1'), ('BO3', 'Melhor de 3'), ('BO5', 'Melhor de 5')], max_length=3, null=True, verbose_name='Formato da partida na final')),
                ('third_place_match', models.BooleanField(default=False, verbose_name='Disputa de 3º lugar')),
                ('seeding_method', models.CharField(choices=[('RANDOM', 'Aleatório'), ('MANUAL', 'Manual')], default='RANDOM', max_length=6, verbose_name='Método de ranqueamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=8, verbose_name='Status da inscrição')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da inscrição')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='championships.championship')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='TiebreakerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(verbose_name='Prioridade do critério de desempate')),
                ('criterion', models.CharField(choices=[('POINTS', 'Pontos'), ('WINS', 'Vitórias'), ('HEAD_TO_HEAD', 'Confronto direto'), ('ROUND_DIFF', 'Saldo de rounds'), ('ROUNDS_WON', 'Rounds vencidos'), ('WIN_RATE', 'Taxa de vitória')], max_length=12, verbose_name='Critério de desempate')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiebreaker_rules', to='championships.championship')),
            ],
            options={
                'verbose_name': 'Regra de Desempate',
                'verbose_name_plural': 'Regras de Desempate',
                'ordering': ['priority'],
            },
        ),
    ]
