# Generated by Django 6.0.5 on 2026-05-21 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='championshipstaff',
            constraint=models.UniqueConstraint(fields=('championship', 'user'), name='unique_user_per_championship_staff'),
        ),
        migrations.AddConstraint(
            model_name='championshipstaff',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'OWNER')), fields=('championship',), name='unique_owner_per_championship'),
        ),
    ]
