# Generated by Django 6.0.5 on 2026-05-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiebreakerrule',
            options={'ordering': ['championship__name', 'priority'], 'verbose_name': 'Regra de Desempate', 'verbose_name_plural': 'Regras de Desempate'},
        ),
        migrations.AlterField(
            model_name='championship',
            name='group_count',
            field=models.PositiveIntegerField(blank=True, help_text='Para pontos corridos: deve ser 1. Para fase de grupos: defina a quantidade de grupos.', null=True, verbose_name='Número de grupos'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='teams_advancing_per_group',
            field=models.PositiveIntegerField(blank=True, help_text='Em pontos corridos deve ser 0.', null=True, verbose_name='Número de times que avançam por grupo'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='teams_per_group',
            field=models.PositiveIntegerField(blank=True, help_text='Em pontos corridos deve ser igual ao número máximo de times.', null=True, verbose_name='Número de times por grupo'),
        ),
    ]
