# Generated by Django 6.0.5 on 2026-06-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='message',
            field=models.TextField(blank=True, verbose_name='Mensagem'),
        ),
        migrations.AddField(
            model_name='invite',
            name='proposed_role',
            field=models.CharField(blank=True, max_length=80, verbose_name='Função proposta'),
        ),
        migrations.AddField(
            model_name='team',
            name='accent_color',
            field=models.CharField(blank=True, default='#4cd7f6', max_length=7, verbose_name='Cor de destaque'),
        ),
        migrations.AddField(
            model_name='team',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='team_banners', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='team',
            name='primary_color',
            field=models.CharField(blank=True, default='#d0bcff', max_length=7, verbose_name='Cor primária'),
        ),
        migrations.AddField(
            model_name='team',
            name='primary_game',
            field=models.CharField(blank=True, max_length=80, verbose_name='Jogo principal'),
        ),
        migrations.AddField(
            model_name='team',
            name='public_recruitment',
            field=models.BooleanField(default=True, verbose_name='Recrutamento público'),
        ),
        migrations.AddField(
            model_name='team',
            name='region',
            field=models.CharField(blank=True, max_length=80, verbose_name='Região'),
        ),
        migrations.AddField(
            model_name='team',
            name='social_url',
            field=models.URLField(blank=True, verbose_name='URL social'),
        ),
        migrations.AddField(
            model_name='team',
            name='tag',
            field=models.CharField(blank=True, max_length=4, verbose_name='Tag da equipe'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='role',
            field=models.CharField(blank=True, default='Jogador', max_length=80, verbose_name='Função'),
        ),
    ]
