# Generated by Django 6.0.5 on 2026-05-20 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('championships', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField(verbose_name='Número da Partida')),
                ('score_a', models.IntegerField(default=0, verbose_name='Pontuação Time A')),
                ('score_b', models.IntegerField(default=0, verbose_name='Pontuação Time B')),
                ('map_name', models.CharField(blank=True, max_length=80, verbose_name='Mapa')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='teams.team', verbose_name='Vencedor')),
            ],
            options={
                'verbose_name': 'Resultado da Partida',
                'verbose_name_plural': 'Resultado das Partidas',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championships.championship', verbose_name='Campeonato')),
            ],
            options={
                'verbose_name': 'Grupo',
            },
        ),
        migrations.CreateModel(
            name='GroupStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0, verbose_name='Vitórias')),
                ('losses', models.IntegerField(default=0, verbose_name='Derrotas')),
                ('draws', models.IntegerField(blank=True, null=True, verbose_name='Empates')),
                ('points', models.IntegerField(default=0, verbose_name='Pontuação')),
                ('rounds_won', models.IntegerField(default=0, verbose_name='Rounds Vencidos')),
                ('rounds_lost', models.IntegerField(default=0, verbose_name='Rounds Perdidos')),
                ('round_diff', models.IntegerField(default=0, verbose_name='Diferença de Rounds')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='Posição')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.group', verbose_name='Grupo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(related_name='groups', through='matches.GroupStanding', to='teams.team', verbose_name='Times'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_format', models.CharField(choices=[('BO1', 'Best of 1'), ('BO3', 'Best of 3'), ('BO5', 'Best of 5')], max_length=5, verbose_name='Formato')),
                ('phase', models.CharField(choices=[('GROUP', 'Grupos'), ('PLAYOFF', 'Playoff'), ('GRAND_FINAL', 'Grande Final')], max_length=12, verbose_name='Fase')),
                ('playoff_round', models.IntegerField(blank=True, null=True, verbose_name='Rodada do Playoff')),
                ('round_number', models.IntegerField(verbose_name='Rodada')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('ONGOING', 'Em Andamento'), ('FINISHED', 'Encerrado')], max_length=12, verbose_name='Status')),
                ('scheduled_at', models.DateField(blank=True, null=True, verbose_name='Agendado Para')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championships.championship', verbose_name='Campeonato')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.group', verbose_name='Grupo')),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team_a', to='teams.team', verbose_name='Time A')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team_b', to='teams.team', verbose_name='Time B')),
                ('teams', models.ManyToManyField(related_name='game_results', through='matches.GameResult', to='teams.team', verbose_name='Times')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='teams.team', verbose_name='Vencedor')),
            ],
            options={
                'verbose_name': 'Partida',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='gameresult',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match', verbose_name='Partida'),
        ),
        migrations.AddConstraint(
            model_name='groupstanding',
            constraint=models.UniqueConstraint(fields=('group', 'team'), name='unique_group_team'),
        ),
        migrations.AddConstraint(
            model_name='gameresult',
            constraint=models.UniqueConstraint(fields=('match_id', 'game_number'), name='unique_match_number'),
        ),
    ]
