# Generated by Django 6.0.5 on 2026-05-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_format',
            field=models.CharField(
                choices=[
                    ('BO1', 'Melhor de 1'),
                    ('BO3', 'Melhor de 3'),
                    ('BO5', 'Melhor de 5'),
                ],
                max_length=5,
                verbose_name='Formato',
            ),
        ),
    ]
