# Generated by Django 6.0.5 on 2026-05-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_match_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameresult',
            options={'ordering': ['match_id', 'game_number'], 'verbose_name': 'Resultado da Partida', 'verbose_name_plural': 'Resultado das Partidas'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['championship', 'name'], 'verbose_name': 'Grupo'},
        ),
        migrations.AlterModelOptions(
            name='groupstanding',
            options={'ordering': ['group', 'position'], 'verbose_name': 'Classificação', 'verbose_name_plural': 'Classificações'},
        ),
    ]
